### ISSUE TITLE
chillkernelslicerange() bug

### ISSUE THREAD

**Issue by EduardoFernandezC** [CWWhitney/pasitR#7]
Hey @CWWhitney I found a bug in this function. When selecting a wide range lets say 40 CP the functions produces an error. Is it normal because of the method behind? Otherwise, we could add a Stop for limiting the width of the range.

**Comment by CWWhitney** [comment]
Hi Eduardo, 

This really does appear to be a bug. 
If you ave an idea about how to implement the ’stop’ please do so. 

On Dec 13, 2019, at 6:07 PM, Eduardo Fernandez C <notifications@github.com> wrote:

Hey @CWWhitney I found a bug in this function. When selecting a wide range lets say 40 CP the functions produces an error. Is it normal because of the method behind? Otherwise, we could add a Stop for limiting the width of the range.

**Comment by EduardoFernandezC** [comment]
@CWWhitney no problems on this one. Maybe I made a mistake when evaluating the function. Sorry for the false announcement.

**Comment by CWWhitney** [comment]
No worries.
